# run: conda env create --file conda-env.yml
name: jesperdramsch-segam18
channels:
  - conda-forge
dependencies:
  - python=3.6
  - scikit-learn
  - tensorflow-gpu
  - keras
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - obspy
  - pip:
    - keras-tqdm